### ISSUE TITLE
Update BIKE code

### ISSUE THREAD

**Issue by jschanck** [open-quantum-safe/liboqs#887]
We're currently shipping BIKE 3.2, the latest version is 4.1 (10/08/2020). https://bikesuite.org/

This is a good target for copy_from_upstream #883, since BIKE is not in PQClean.

**Comment by dstebila** [comment]
Tagging @drucker-nir and @crockeea

**Comment by baentsch** [comment]
#883 has landed (thanks @bhess) and really looks like a nice way to automatically include _any_ upstream code now (initial doc [here](https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#automated-inclusion)).

**Comment by drucker-nir** [comment]
Tagging @dkostic and @Shay-Gueron

**Comment by dkostic** [comment]
Hi all, we've finally got some time to do the import of BIKE Round-3 (#1013). I published the PR but there are some issues with cygwin reported by the CI. I'm not very familiar with LibOQS CI tests so I'd really appreciate any help with the error messages so that I could quickly push the fix.

**Comment by baentsch** [comment]
Just looking at the first error message
```
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/kem/bike/CMakeFiles/bike1_l3_cpa.dir/kem_bike.c.o:kem_bike.c:(.text$OQS_KEM_bike1_l1_cpa_new+0x0): multiple definition of `OQS_KEM_bike1_l1_cpa_new'; src/kem/bike/CMakeFiles/bike1_l1_cpa.dir/kem_bike.c.o:kem_bike.c:(.text$OQS_KEM_bike1_l1_cpa_new+0x0): first defined here
```
this seems to be a (hopefully simple) namespace problem for some reason not resolved for cygwin: Why otherwise would a `bike1_l3_cpa` folder generate a symbol like `OQS_KEM_bike1_l1_cpa_new`? But I also have to admit I have not been involved in the previous round of integrating/getting BIKE to "play nice" wrt namespaces; tagging @xvzcf @dstebila or @jschanck to check if they know where to look (?)

**Comment by dkostic** [comment]
Yeah, I'm looking into that but I can't figure out why it does it. I've been testing on Ubuntu and everything builds correctly. Thanks for your help, I'll keep debugging!

**Comment by dkostic** [comment]
I think I fixed this one, let's see what comes up next.
